export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export EDITOR='nvim'
export VISUAL='nvim'
HISTFILE=$HOME/.zhistory
SAVEHIST=10000
HISTSIZE=10000
export TERM=tmux-256color
export COLORTERM=truecolor
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"
export FZF_DEFAULT_OPTS='
--color=fg:#908caa,bg:-1,hl:#ebbcba
--color=fg+:#e0def4,bg+:-1,hl+:#ebbcba
--color=border:#403d52,header:#31748f,gutter:-1
--color=spinner:#f6c177,info:#9ccfd8
--color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa'
