#!/usr/bin/env bash
set -e

function linking() {
  ln -sfn $(pwd)/.zshrc ~/.zshrc
  ln -sfn $(pwd)/.zshenv ~/.zshenv
  ln -sfn $(pwd)/.tmux.conf ~/.tmux.conf
  ln -sfn $(pwd)/.psqlrc ~/.psqlrc
  ln -sfn $(pwd)/.vimrc ~/.vimrc
  ln -sfn $(pwd)/.ideavimrc ~/.ideavimrc

  mkdir -p ${XDG_DATA_HOME:=~/.local/share}
  mkdir -p ${XDG_CONFIG_HOME:=~/.config}
  ln -sfn $(pwd)/nvim $XDG_CONFIG_HOME/nvim

  ln -sfn $(pwd)/.gitignore ~/.gitignore
  git config --global core.excludesFile '~/.gitignore'

  mkdir -p ~/.local/bin
  mkdir -p ~/personal
  mkdir -p ~/repos
  touch ~/.profile
}
echo '[-] linking dotfiles [-]'
linking

if [[ "$OSTYPE" == "darwin"* ]]; then
  if ! xcode-select -p &> /dev/null; then
    echo '[-] installing xcode command line tools [-]'
    xcode-select --install
  fi
  if ! hash brew &> /dev/null; then
    echo '[-] installing homebrew [-]'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    (echo; echo 'eval "$(/opt/homebrew/bin/brew shellenv)"') >> ~/.zprofile
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi

  echo '[-] installing essential packages [-]'
  brew update
  brew install curl wget git coreutils watch ncdu cmake ninja tree parallel tmux fzf
  brew install ripgrep jq golang htop pdfgrep hyperfine procs maccy universal-ctags font-hack
else
  echo '[-] checking secure boot state [-]'
  if [[ "$(mokutil --sb-state)" != *"SecureBoot enabled"* ]]; then
    echo "could not determine the secure boot state."
    exit 1
  fi

  if [ ! -f '/etc/apt/sources.list.d/debian.sources' ]; then
    echo '[-] configuring debian sources [-]'
    sudo cp -f $(pwd)/etc/apt/sources.list.d/debian.sources /etc/apt/sources.list.d/debian.sources
    sudo apt update
    sudo apt install -y apt-listchanges apt-listbugs
    sudo apt full-upgrade -y
  fi

  echo '[-] installing essential packages [-]'
  sudo apt update && sudo apt upgrade -y
  sudo apt install -y curl wget zip zsh git coreutils gcc clang clangd cmake make ninja-build ca-certificates
  sudo apt install -y watch ncdu autoconf automake parallel make pkg-config flex bison check meson
  sudo apt install -y tree vim tmux fzf ripgrep jq universal-ctags wl-clipboard htop gnupg2 pdfgrep hyperfine procs

  if lspci | grep -E "VGA|3D" | grep -iq "AMD"; then
    echo '[-] installing amd essential packages [-]'
    ln -sfn $(pwd)/MangoHud $XDG_CONFIG_HOME/MangoHud
    sudo apt install -y rocm-smi gamemode gamescope flatpak gnome-software-plugin-flatpak
    flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
    flatpak install flathub com.github.tchx84.Flatseal
  fi

  if [ ! -f '/etc/apt/keyrings/docker.asc' ]; then
    echo '[-] configuring docker rootless mode [-]'
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt update
    sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin docker-ce-rootless-extras
    dockerd-rootless-setuptool.sh install
  fi

  target_dir=$XDG_DATA_HOME/fonts
  if [ ! -d "$target_dir" ] ; then
    echo '[-] installing favourite font [-]'
    wget https://github.com/source-foundry/Hack/releases/download/v3.003/Hack-v3.003-ttf.zip
    mkdir -p $target_dir
    unzip Hack-v3.003-ttf.zip -d $target_dir
    rm -f Hack-v3.003-ttf.zip
    fc-cache -f -v
  fi

  target_dir=$XDG_DATA_HOME/ibus-bamboo
  if [ ! -d "$target_dir" ] ; then
    echo '[-] building ibus-bamboo [-]'
    sudo apt install -y ibus make golang libx11-dev libxtst-dev libgtk-3-dev
    git clone https://github.com/BambooEngine/ibus-bamboo.git $target_dir
    cd $target_dir
    sudo make install PREFIX=/usr
    env DCONF_PROFILE=ibus dconf write /desktop/ibus/general/preload-engines "['BambooUs', 'Bamboo']" && gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('ibus', 'Bamboo')]"
  fi
fi

echo '[-] downloading git-prompt.sh script [-]'
mkdir -p ~/.zsh/plugins/git/
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh \
  -o ~/.zsh/plugins/git/git-prompt.sh

target_dir=~/.zsh/zsh-autosuggestions
if [ ! -d "$target_dir" ] ; then
  echo '[-] cloning zsh-autosuggestions [-]'
  git clone https://github.com/zsh-users/zsh-autosuggestions $target_dir
fi

target_dir=$XDG_DATA_HOME/neovim
if [ ! -d "$target_dir" ] ; then
  echo '[-] building neovim [-]'
  git clone https://github.com/neovim/neovim.git $target_dir
  cd $target_dir
  # git checkout nightly
  make CMAKE_BUILD_TYPE=RelWithDebInfo
  sudo make install
fi

current_shell=$(echo $SHELL)
if [ "$current_shell" != '/usr/bin/zsh' ] && [ "$current_shell" != '/bin/zsh' ]; then
  echo '[-] change default shell to zsh [-]'
  chsh -s $(which zsh)
  echo '[-] device ready, restart your computer. [-]'
else
  echo '[-] device ready. [-]'
fi

# vim: ft=bash
